apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-world-pipeline-run
spec:
  pipelineRef:
    name: hello-world-pipeline
  params:
    - name: git-url
      value: "https://github.com/bartholomaeuss/hello-go"
    - name: git-revision
      value: "main"
    - name: branch
      value: "main"
