apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-build-task
spec:
  params:
    - name: git-url
      type: string
      description: "The git repository URL"
    - name: git-revision
      type: string
      description: "The branch or commit to checkout"
  steps:
    - name: clone-repo
      image: alpine/git
      script: |
        #!/bin/sh
        git clone $(params.git-url) /workspace/source
        cd /workspace/source
        git checkout $(params.git-revision)
    - name: go-build
      image: golang:1.23.1
      workingDir: /workspace/source
      script: |
        go mod tidy
        go build -o hello-world-binary main.go
